language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcunit1 libcunit1-doc libcunit1-dev
before_script:
  - cmake .
script:
  - make
  - make test
