language: c
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-7
      - clang-5.0

matrix:
  include:
    - compiler: gcc
      env: CXX=g++-7

    - compiler: clang
      env: CXX=clang++-5.0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcunit1 libcunit1-doc libcunit1-dev

script:
  - mkdir -p ../libuast-build && cd ../libuast-build && cmake ../libuast && make && make test
  - cd $TRAVIS_BUILD_DIR

before_deploy:
  - sh scripts/update-version.sh
  - git archive --prefix "libuast-${TRAVIS_TAG}/" --output "libuast-${TRAVIS_TAG}.tar.gz" `git stash create`

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: libuast-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
