sudo: required
language: generic # using C will override the specified compilers with trusty's default

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      env: CC='gcc-6' CXX='g++-6'
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6 # for newer libs that clang'll use
            - g++-6
            - clang
      env: CC='clang' CXX='clang++'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcunit1 libcunit1-doc libcunit1-dev

script:
  - mkdir -p ../libuast-build && cd ../libuast-build && cmake ../libuast && make && make test
  - cd $TRAVIS_BUILD_DIR

before_deploy:
  - sh scripts/update-version.sh
  - git archive --prefix "libuast-${TRAVIS_TAG}/" --output "libuast-${TRAVIS_TAG}.tar.gz" `git stash create`

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: libuast-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
